spring.application.name=cropdeal-fresh-frontend
server.port=8095
management.endpoints.web.exposure.include=health,info
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
